"""Schema spec for the Genpact F&A master-data tables.

Single source of truth for three consumers so they cannot drift:

* ``app/models/genpact_master_data.py`` — builds SQLAlchemy Core ``Table``
  objects on ``Base.metadata`` from this spec (so Alembic autogenerate
  sees them and the ORM ``Base`` can create them).
* the Alembic migration that creates the tables (autogenerated from the
  metadata above).
* ``scripts/seed_genpact_master_data.py`` — reads the workbook and bulk
  inserts rows, applying the per-column coercion declared here.

The source workbook (``Genpact_FA_Synthetic_Employee_Dataset.xlsx``) has
many sheets. The clearly-structured ones each become one table, scoped
to a single tenant via a ``tenant_id`` column. Columns are mapped
**positionally** (spec order == sheet column order) because several
sheet headers contain trailing spaces / typos that make name matching
fragile. ``header_row`` is the 0-based row that holds the headers; data
starts on the row after it.

A column spec is ``(attr, kind, length_or_precision)``:

* ``kind`` is one of ``str | text | int | bigint | num | date | bool``.
* for ``str`` the 3rd item is the ``String`` length.
* for ``num`` the 3rd item is the ``(precision, scale)`` tuple.
* otherwise the 3rd item is ``None``.

Blank cells are coerced to a type default (never NULL) so downstream
consumers can rely on non-null business columns.
"""

from __future__ import annotations

import datetime

DATE_SENTINEL = datetime.date(1970, 1, 1)


# --- 1. Employee Master (sheet "1. Employee Master", header row 0) ---------
EMPLOYEE_MASTER_COLUMNS = [
    ("employee_id", "str", 16),
    ("employee_name", "str", 128),
    ("fiscal_year", "str", 16),
    ("job_position_id", "str", 64),
    ("employment_type", "str", 64),
    ("status", "str", 16),
    ("exit_classification", "str", 64),
    ("exit_date", "date", None),
    ("joining_date", "date", None),
    ("gender", "str", 32),
    ("business_unit", "str", 64),
    ("department", "str", 64),
    ("job_family", "str", 64),
    ("designation", "str", 128),
    ("job_level", "str", 8),
    ("previous_job_level", "str", 8),
    ("manager_employee_id", "str", 16),
    ("manager_job_band", "str", 8),
    ("span_direct", "int", None),
    ("span_indirect", "int", None),
    ("location_city", "str", 96),
    ("work_mode", "str", 16),
    ("performance_rating", "num", (5, 2)),
    ("performance_rating_category", "str", 64),
    ("promotion_flag", "bool", None),
    ("last_promotion_date", "date", None),
    ("company_experience_years", "num", (6, 2)),
    ("total_experience_years_1", "num", (6, 2)),
    ("currency", "str", 3),
    ("base_salary_pre", "bigint", None),
    ("base_salary_post", "bigint", None),
    ("base_increment_pct", "num", (8, 4)),
    ("target_variable_pct", "num", (8, 4)),
    ("variable_pre", "bigint", None),
    ("variable_post", "bigint", None),
    ("variable_increment_pct", "num", (8, 4)),
    ("total_increment_pct", "num", (8, 4)),
    ("tcc_pre", "bigint", None),
    ("tcc_post", "bigint", None),
    ("total_rewards_pre", "bigint", None),
    ("total_rewards_post", "bigint", None),
    ("lti_eligible", "bool", None),
    ("lti_grant_value", "bigint", None),
    ("lti_type", "str", 32),
    ("grant_date", "date", None),
    ("vesting_total_years", "int", None),
    ("vesting_cliff_years", "int", None),
    ("lti_unvested_remaining", "bigint", None),
    ("next_vesting_date", "date", None),
    ("total_experience_years_2", "num", (6, 2)),
    ("promotion_flag_upcoming", "bool", None),
    ("post_promotion_level", "str", 8),
    ("post_promotion_department", "str", 64),
    ("internal_compa_pre", "num", (8, 4)),
    ("internal_compa_post", "num", (8, 4)),
    ("external_compa_pre", "num", (8, 4)),
    ("external_compa_post", "num", (8, 4)),
]

# --- 2. Job Posting (sheet "2. Job Posting", header row 0) ------------------
JOB_POSTING_COLUMNS = [
    ("position_id", "str", 64),
    ("leaver_employee_id", "str", 16),
    ("resignation_date", "date", None),
    ("posting_date", "date", None),
    ("offer_accept_date", "date", None),
    ("offers_extended", "int", None),
    ("offer_outcome", "str", 32),
    ("date_of_joining_replacement", "date", None),
    ("pct_hike_over_previous_job", "str", 32),
    ("agency_fee_paid", "bigint", None),
    ("recruiter_cost_estimate", "bigint", None),
    ("onboarding_cost", "bigint", None),
    ("leaver_last_working_day", "date", None),
    ("leaver_base_salary", "bigint", None),
    ("hire_type", "str", 32),
    ("notice_period_days", "int", None),
    ("ttf_days", "int", None),
    ("new_hire_base_salary", "bigint", None),
    ("vacancy_gap_days", "int", None),
    ("salary_premium", "bigint", None),
    ("business_unit", "str", 64),
    ("job_family", "str", 64),
    ("job_level", "str", 8),
    ("exit_reason", "str", 96),
]

# --- 4..7 Benchmark 20xx (one table, unioned across the 4 sheets) ----------
BENCHMARK_COLUMNS = [
    ("benchmark_source", "str", 64),
    ("business_unit", "str", 64),
    ("department", "str", 64),
    ("job_family", "str", 64),
    ("designation", "str", 128),
    ("job_level", "str", 8),
    ("currency", "str", 3),
    ("geography", "str", 64),
    ("survey_source", "str", 96),
    ("survey_year", "int", None),
    ("base_p25", "bigint", None),
    ("base_p50", "bigint", None),
    ("base_p75", "bigint", None),
    ("base_p90", "bigint", None),
]

# --- 8. Currency Master ----------------------------------------------------
CURRENCY_MASTER_COLUMNS = [
    ("reporting_cycle", "str", 16),
    ("reporting_currency", "str", 3),
    ("local_currency", "str", 3),
    ("conversion_value", "num", (14, 6)),
]

# --- 9. Talent_India (header on row 1 / 0-based index 1) --------------------
TALENT_SUPPLY_COLUMNS = [
    ("industry", "str", 64),
    ("job_family", "str", 64),
    ("region", "str", 64),
    ("core_discipline", "str", 128),
    ("annual_graduates_india", "bigint", None),
    ("projected_supply_2030", "bigint", None),
    ("assumptions_notes", "text", None),
    ("implied_cagr_pct", "num", (8, 3)),
]

# --- 11. AI_Impact (header on row 1) ---------------------------------------
AI_IMPACT_COLUMNS = [
    ("industry", "str", 64),
    ("job_family", "str", 64),
    ("geography", "str", 64),
    ("ai_exposure_score", "int", None),
    ("demand_outlook", "str", 64),
    ("net_talent_position", "str", 64),
    ("how_ai_reshapes_role", "text", None),
    ("annual_graduate_supply", "bigint", None),
    ("projected_supply_2030", "bigint", None),
    ("supply_vs_demand_signal", "str", 64),
]

# --- 12. Comp_Outlook (header on row 1) ------------------------------------
COMP_OUTLOOK_COLUMNS = [
    ("industry", "str", 64),
    ("job_family", "str", 64),
    ("geography", "str", 64),
    ("salary_band_mid_level", "str", 96),
    ("typical_increment_2025_pct", "num", (8, 3)),
    ("projected_increment_2027_pct", "num", (8, 3)),
    ("increment_delta", "num", (8, 3)),
    ("compensation_trend", "str", 64),
    ("ai_skills_premium_pct", "num", (8, 3)),
    ("demand_outlook", "str", 64),
    ("net_talent_position", "str", 64),
    ("compensation_narrative", "text", None),
]

# --- 3. Pay Policy (unstructured -> stored as raw text rows) ----------------
PAY_POLICY_RAW_COLUMNS = [("row_num", "int", None)] + [(f"c{i}", "str", 512) for i in range(1, 15)]


# sheet_name -> (table_name, header_row, columns)
TABLES = {
    "1. Employee Master": ("genpact_employee_master", 0, EMPLOYEE_MASTER_COLUMNS),
    "2. Job Posting": ("genpact_job_posting", 0, JOB_POSTING_COLUMNS),
    "8. Currency Master": ("genpact_currency_master", 0, CURRENCY_MASTER_COLUMNS),
    "9. Talent_India": ("genpact_talent_supply", 1, TALENT_SUPPLY_COLUMNS),
    "11. AI_Impact": ("genpact_ai_impact", 1, AI_IMPACT_COLUMNS),
    "12. Comp_Outlook": ("genpact_comp_outlook", 1, COMP_OUTLOOK_COLUMNS),
    "3. Pay Policy": ("genpact_pay_policy_raw", 0, PAY_POLICY_RAW_COLUMNS),
}

# The four yearly benchmark sheets all land in one table.
BENCHMARK_SHEETS = (
    "4. Benchmark 2023",
    "5. Benchmark 2024",
    "6. Benchmark 2025",
    "7. Benchmark 2026",
)
BENCHMARK_TABLE = ("genpact_benchmark", 0, BENCHMARK_COLUMNS)


def coerce(kind: str, value):
    """Coerce a raw cell value to the column's Python type, filling blanks."""
    blank = value is None or (isinstance(value, str) and value.strip() == "")
    if kind in ("str", "text"):
        return "" if blank else str(value).strip()
    if kind in ("int", "bigint"):
        if blank:
            return 0
        try:
            return round(float(value))
        except (TypeError, ValueError):
            return 0
    if kind == "num":
        if blank:
            return 0
        try:
            return float(value)
        except (TypeError, ValueError):
            return 0
    if kind == "bool":
        if blank:
            return False
        if isinstance(value, bool):
            return value
        return str(value).strip().upper() in ("TRUE", "1", "YES", "Y")
    if kind == "date":
        if blank:
            return DATE_SENTINEL
        if isinstance(value, datetime.datetime):
            return value.date()
        if isinstance(value, datetime.date):
            return value
        return DATE_SENTINEL
    raise ValueError(f"unknown kind: {kind}")
